version: '2'

services:

  mongoose-node:
    image: $IMAGE_NAME:$IMAGE_TAG
    command: ["--run-node"]
    ports:
      - "1090-1098:1099"
      - "9990-9998:9999"

  mongoose:
    image: $IMAGE_NAME:$IMAGE_TAG
    container_name: mongoose
    ports:
      - "1099:1099"
      - "9999:9999"
    volumes:
      - "${MONGOOSE_SCENARIO_PATH}:/opt/volume/scenario.js"
    command: ["--storage-auth-uid=${STORAGE_AUTH_UID}",
              "--storage-auth-secret=${STORAGE_AUTH_SECRET}",
              "--storage-net-node-addrs=${STORAGE_NET_NODE_ADDRS}",
              "--load-step-node-addrs=${LOAD_STEP_NODE_ADDRS}",
              "--run-scenario=/opt/volume/scenario.js",
              "--item-output-path=${ITEM_OUTPUT_PATH}"]
    links:
      - mongoose-node
    depends_on:
      - mongoose-node
