version: '3.8'

services:

  mongoose-node:
    image: ${IMAGE:-emcmongoose/mongoose-base}:${TAG:-4.2.16}
    command: ["--run-node"]
    container_name: mongoose-node
    hostname: mongoose-node
    ports:
      - "1099:1099"
      - "9999:9999"
      - "5005:5005"
    deploy:
      replicas: ${REPLICAS:-1}
      placement:
        max_replicas_per_node: 1
