version: '3.7'

services:
  minio:
    image: minio/minio:latest
    hostname: minio
    environment:
      - MINIO_ACCESS_KEY=user1
      - MINIO_SECRET_KEY=secretKey1
    volumes:
      - minio-data:/export
    ports:
      - "9000:9000"
    command: server /data

volumes:
  minio-data:
