version: '3'

services:
  mongoose-node:
    image: ${IMAGE:-emcmongoose/mongoose-base}:${TAG:-latest}
    command: ["--run-node"]
    hostname: mongoose-node
    ports:
      - "1090-1098:1099"
      - "9990-9998:9999"
